version: "3.8"

services:
  mongo:
    image: mongo
    container_name: formbuilder-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: formbuilder-backend
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017/?authSource=admin
      - PORT=5001

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: formbuilder-frontend
    ports:
      - "3000:80" # React build served via NGINX (internal port 80)
    depends_on:
      - server
